# Configuration for librarian-puppet.
forge "http://forge.puppetlabs.com"
mod "example42/timezone"
mod "example42/puppi"
mod "puppetlabs/apt"
mod "puppetlabs/concat"
mod "puppetlabs/firewall"
mod "puppetlabs/stdlib"
mod "jfryman/nginx"
mod "puppetlabs/vcsrepo"
